"""Generate, persist, and list portable launch scripts for discovered models.

The Llama Control Center app manages GGUF models that live in user-configured
or auto-detected model folders. Originally, every model entry in ``models.json``
referenced a hand-written PowerShell launch script (for example
``start-tiny-1b-server.ps1``). That worked when the user pre-authored every
script, but it broke the moment a new model was dropped into the models
folder: the dashboard would resolve the profile but could not launch it
because the referenced script did not exist.

This module closes that gap. It produces the same style of portable launch
script the project has always shipped (a tiny ``$ErrorActionPreference = 'Stop'``
PowerShell file that calls ``llama-server`` with the resolved arguments),
so generated scripts are interchangeable with the hand-written ones and the
existing :mod:`lcc_core.manifest` parser picks them up unchanged.

The module also writes a POSIX ``.sh`` companion on every generation so the
same generated set works on Linux/macOS without an extra conversion step.

Public API:

- :func:`generate_launch_script` -- build script text + write to disk for a
  single resolved profile.
- :func:`generate_all_launch_scripts` -- scan model folders and (re)generate
  every script, including ones for newly-added models that have no manifest
  entry yet.
- :func:`list_launch_scripts` -- enumerate the generated scripts on disk.
- :func:`delete_launch_script` -- remove a generated script.
- :func:`launch_scripts_scan_summary` -- describe the most recent scan so the
  UI/API can report what changed.
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .config import AppConfig
from .llama_args import build_llama_server_args
from .models import discover_models
from .paths import (
    find_project_root,
    is_windows,
    launch_scripts_dir,
)
from .profile_resolver import resolve_profiles


SCRIPT_GENERATED_MARKER = "Auto-generated by Llama Control Center"

SCRIPT_HEADER_COMMENT = (
    f"# {SCRIPT_GENERATED_MARKER}. Edit recommended_params in\n"
    "# models.json (or the in-app Parameters panel) and rescan to refresh.\n"
)


def _is_generated_script(path: Path) -> bool:
    """True if ``path`` was produced by this module (carries our marker)."""

    try:
        return SCRIPT_GENERATED_MARKER in path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False

SAFE_FILENAME_RE = re.compile(r"[^a-zA-Z0-9._-]+")


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _safe_slug(value: str, fallback: str = "model") -> str:
    slug = SAFE_FILENAME_RE.sub("-", value or "").strip("-").lower()
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug or fallback


def script_dir(project_root: str | Path | None = None) -> Path:
    """Directory the generated scripts are written to.

    When a project root is available the scripts go to ``<root>/scripts`` so
    the existing :mod:`lcc_core.manifest` parser (which looks in ``<root>`` and
    ``<root>/scripts``) discovers them and can pin an exact model path. With no
    project root we fall back to the per-user cache directory.
    """

    root = Path(project_root).expanduser() if project_root else find_project_root()
    if root:
        path = Path(root) / "scripts"
    else:
        path = launch_scripts_dir()
    path.mkdir(parents=True, exist_ok=True)
    return path


def state_path() -> Path:
    base = launch_scripts_dir()
    base.mkdir(parents=True, exist_ok=True)
    return base / "launch-scripts-state.json"


def _norm_path(value: str) -> str:
    try:
        return str(Path(value).expanduser().resolve()).lower()
    except OSError:
        return str(value or "").lower()


DRAFT_NAME_RE = re.compile(r"(?i)(?:^|[-_.])(?:mtp|draft)(?:[-_.]|$)")


def _is_draft_model(model_path: str) -> bool:
    """Heuristically detect speculative/draft companion models.

    These are consumed via a profile's ``draft_model`` parameter and must not
    be launched as standalone servers, so they never get a starter script.
    """

    path = Path(model_path)
    parts = {segment.lower() for segment in path.parts}
    if "mtp" in parts or "draft" in parts:
        return True
    return bool(DRAFT_NAME_RE.search(path.name))


MANIFEST_PARAM_KEYS = (
    "runtime",
    "ctx_size",
    "threads",
    "threads_batch",
    "batch_size",
    "ubatch_size",
    "gpu_layers",
    "cache_type_k",
    "cache_type_v",
    "flash_attn",
    "reasoning",
    "reasoning_budget",
    "cache_ram_mib",
    "cache_reuse",
    "slot_prompt_similarity",
)


def _manifest_params(params: dict[str, Any]) -> dict[str, Any]:
    """Trim a full param set down to the keys stored in models.json."""

    return {key: params[key] for key in MANIFEST_PARAM_KEYS if key in params}


def _manifest_path(root: Path | None) -> Path | None:
    return (Path(root) / "models.json") if root else None


def _load_manifest_doc(root: Path | None) -> dict[str, Any]:
    path = _manifest_path(root)
    if not path or not path.is_file():
        return {"models": []}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"models": []}
    if not isinstance(data, dict):
        return {"models": []}
    data.setdefault("models", [])
    if not isinstance(data["models"], list):
        data["models"] = []
    return data


def _save_manifest_doc(root: Path | None, manifest: dict[str, Any]) -> bool:
    path = _manifest_path(root)
    if not path:
        return False
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    tmp.replace(path)
    return True


def _read_state() -> dict[str, Any]:
    path = state_path()
    if not path.is_file():
        return {"last_scan": None, "scripts": {}}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"last_scan": None, "scripts": {}}


def _write_state(state: dict[str, Any]) -> None:
    path = state_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")
    tmp.replace(path)


@dataclass
class GeneratedScript:
    """A single generated launch script on disk."""

    mode: str
    name: str
    model_path: str
    ps1_path: str
    sh_path: str
    command_line: str
    params: dict[str, Any] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class ScanResult:
    """Summary of a generation/scan pass for the API/UI."""

    generated: list[GeneratedScript] = field(default_factory=list)
    skipped: list[dict[str, Any]] = field(default_factory=list)
    errors: list[dict[str, Any]] = field(default_factory=list)
    scanned_model_count: int = 0
    profile_count: int = 0
    scanned_at: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "generated": [item.to_dict() for item in self.generated],
            "skipped": list(self.skipped),
            "errors": list(self.errors),
            "scanned_model_count": int(self.scanned_model_count),
            "profile_count": int(self.profile_count),
            "scanned_at": self.scanned_at,
            "generated_count": len(self.generated),
        }


def _default_params_for_model(model: dict[str, Any], config: AppConfig) -> dict[str, Any]:
    """Pick a reasonable starting parameter set for a freshly discovered model."""

    params: dict[str, Any] = {
        "host": config.default_host or "127.0.0.1",
        "port": int(config.default_port or 8080),
        "alias": Path(model.get("path", "")).stem or model.get("name", "local-model"),
        "ctx_size": 8192,
        "threads": 4,
        "threads_batch": 4,
        "batch_size": 512,
        "ubatch_size": 512,
        "gpu_layers": 999,
        "cache_type_k": "q4_0",
        "cache_type_v": "q4_0",
        "flash_attn": True,
        "kv_offload": True,
        "op_offload": True,
        "acceleration_backend": "auto",
        "device": "auto",
        "mmap": True,
        "reasoning": False,
    }
    params.update(_autotune_params_from_size(model, params))
    return params


def _autotune_params_from_size(model: dict[str, Any], params: dict[str, Any]) -> dict[str, Any]:
    """Tweak defaults based on the model size/quant so the first run fits."""

    overrides: dict[str, Any] = {}
    params_b = model.get("params_b")
    size_bytes = model.get("size_bytes") or 0
    if params_b:
        try:
            params_b = float(params_b)
        except (TypeError, ValueError):
            params_b = None
    if params_b is None and size_bytes:
        # Rough fallback: assume Q4_0 (~4.5 bits/param).
        params_b = max(0.5, (size_bytes * 8) / (4.5 * 1e9))

    if params_b and params_b >= 30:
        overrides["ctx_size"] = 16384
        overrides["batch_size"] = 1024
        overrides["ubatch_size"] = 512
    elif params_b and params_b >= 12:
        overrides["ctx_size"] = 16384
        overrides["batch_size"] = 1024
        overrides["ubatch_size"] = 512
    elif params_b and params_b <= 3:
        overrides["ctx_size"] = 8192
    return overrides


def _render_ps1_classic(
    binary_path: str,
    model_path: str,
    command_argv: list[str],
    params: dict[str, Any],
) -> str:
    """Render a Windows PowerShell launch script in the existing project style.

    The output matches the format of the existing hand-written scripts (e.g.
    ``start-gemma4-26b-a4b-q6k-server.ps1``): a top ``$model`` assignment
    that the manifest parser reads, a ``Test-Path`` guard, and an
    ``& llama-server -m $model ...`` invocation. Drops the leading binary
    path and the ``-m``/``--model`` token (and its argument) from the
    supplied argv because those are emitted explicitly in the script body.
    """

    filtered = _strip_binary_and_model_args(command_argv, binary_path)

    rendered_tokens: list[str] = []
    for token in filtered:
        if not token:
            continue
        if token.startswith("-") or token in {"on", "off"}:
            rendered_tokens.append(token)
        elif token.replace(".", "", 1).isdigit() or token.replace("_", "").isalnum():
            # Numbers, quant names like q4_0, cache types, hosts, etc.
            needs_quotes = " " in token or "/" in token or "\\" in token
            rendered_tokens.append(f"'{token}'" if needs_quotes else token)
        else:
            escaped = token.replace("'", "''")
            rendered_tokens.append(f"'{escaped}'")

    body = " ".join(rendered_tokens).strip()
    posix_model = Path(model_path).as_posix()
    posix_binary = Path(binary_path).as_posix()
    return (
        "$ErrorActionPreference = 'Stop'\n"
        + SCRIPT_HEADER_COMMENT
        + f"$model = '{posix_model}'\n"
        + "if (-not (Test-Path -LiteralPath $model)) { throw \"Missing model: $model\" }\n"
        + f"& '{posix_binary}' -m $model"
        + (f" {body}\n" if body else "\n")
    )


def _strip_binary_and_model_args(command_argv: list[str], binary_path: str) -> list[str]:
    """Drop the leading binary token and the explicit ``-m``/``--model`` arg.

    The launch script renders the binary invocation explicitly (``& 'path'``)
    and the model assignment explicitly (``$model``), so those entries must
    not appear again in the body argv.
    """

    filtered: list[str] = []
    skip_next = False
    for idx, token in enumerate(command_argv):
        if skip_next:
            skip_next = False
            continue
        if idx == 0 and token and Path(token).name == Path(binary_path).name:
            # Drop the binary path that build_llama_server_args inserts at argv[0].
            continue
        if token in {"-m", "--model"}:
            skip_next = True
            continue
        filtered.append(token)
    return filtered


def _render_sh(
    binary_path: str,
    model_path: str,
    command_argv: list[str],
    params: dict[str, Any],
) -> str:
    """Render a POSIX shell launch script for Linux/macOS."""

    filtered = _strip_binary_and_model_args(command_argv, binary_path)

    def shlex_quote(value: str) -> str:
        if value and all(ch.isalnum() or ch in "-_./:=," for ch in value):
            return value
        escaped = value.replace("'", "'\\''")
        return f"'{escaped}'"

    body = " ".join(shlex_quote(token) for token in filtered if token)
    return (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        + SCRIPT_HEADER_COMMENT
        + f"model={shlex_quote(model_path)}\n"
        + "if [[ ! -f \"$model\" ]]; then echo \"Missing model: $model\" >&2; exit 1; fi\n"
        + f"exec {shlex_quote(binary_path)} -m \"$model\""
        + (f" {body}\n" if body else "\n")
    )


def _llama_binary_for_generation(
    project_root: Path | None,
    config: AppConfig,
) -> str | None:
    """Resolve the llama-server binary path used inside generated scripts."""

    from .backends import detect_llama_cpp

    env = detect_llama_cpp(project_root, config=config)
    return env.binary_path


def _binary_path_for_script(
    project_root: Path | None,
    config: AppConfig,
) -> tuple[str | None, list[str]]:
    """Return the binary path to embed and any warnings about it."""

    warnings: list[str] = []
    binary = config.llama_server_path or _llama_binary_for_generation(project_root, config)
    if not binary:
        warnings.append(
            "llama-server was not found; generated scripts use a 'llama-server' placeholder."
        )
        binary = "llama-server"
    return binary, warnings


def _write_text_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8", newline="\n")
    tmp.replace(path)


def generate_launch_script(
    mode: str,
    model_path: str,
    params: dict[str, Any],
    *,
    project_root: str | Path | None = None,
    config: AppConfig | None = None,
    binary_path: str | None = None,
    name: str | None = None,
    overwrite: bool = True,
) -> dict[str, Any]:
    """Generate (or refresh) a single launch script on disk.

    Returns a dictionary with the script paths, rendered command line, and
    any warnings. The dictionary is suitable for direct JSON serialization
    in API responses.
    """

    app_config = config or AppConfig.load()
    root = Path(project_root).expanduser().resolve() if project_root else find_project_root()
    resolved_binary, warnings = _binary_path_for_script(root, app_config)
    binary = binary_path or resolved_binary

    safe_params = dict(params)
    safe_params.setdefault("host", app_config.default_host or "127.0.0.1")
    safe_params.setdefault("port", int(app_config.default_port or 8080))
    safe_params.setdefault("alias", Path(model_path).stem or mode)

    command = build_llama_server_args(
        binary,
        model_path,
        safe_params,
        extra_args=app_config.extra_llama_args,
    )
    warnings.extend(command.warnings)

    slug = _safe_slug(mode or Path(model_path).stem)
    scripts_root = script_dir(root)
    ps1_path = scripts_root / f"{slug}.ps1"
    sh_path = scripts_root / f"{slug}.sh"

    if not overwrite and (ps1_path.is_file() or sh_path.is_file()):
        return {
            "mode": mode,
            "name": name or mode,
            "model_path": model_path,
            "ps1_path": str(ps1_path),
            "sh_path": str(sh_path),
            "command_line": command.command_line,
            "params": safe_params,
            "warnings": warnings,
            "skipped": True,
        }

    # Never clobber a hand-written script that happens to share this directory
    # (e.g. switch-model.ps1 and other infrastructure files under <root>/scripts).
    if ps1_path.is_file() and not _is_generated_script(ps1_path):
        warnings.append(
            f"Refusing to overwrite hand-written script {ps1_path.name}; "
            "skipped to protect existing file."
        )
        return {
            "mode": mode,
            "name": name or mode,
            "model_path": model_path,
            "ps1_path": str(ps1_path),
            "sh_path": str(sh_path),
            "command_line": command.command_line,
            "params": safe_params,
            "warnings": warnings,
            "skipped": True,
        }

    ps1_text = _render_ps1_classic(binary, model_path, command.argv, safe_params)
    _write_text_atomic(ps1_path, ps1_text)

    # The POSIX companion is only useful off-Windows. On Windows the embedded
    # model/binary paths are drive-letter absolute, so a .sh would never run;
    # skip it to avoid shipping dead files.
    wrote_sh = not is_windows()
    if wrote_sh:
        sh_text = _render_sh(binary, model_path, command.argv, safe_params)
        _write_text_atomic(sh_path, sh_text)

    record = GeneratedScript(
        mode=mode,
        name=name or mode,
        model_path=model_path,
        ps1_path=str(ps1_path),
        sh_path=str(sh_path) if wrote_sh else "",
        command_line=command.command_line,
        params=safe_params,
        warnings=warnings,
    )
    _record_state(record)
    payload = record.to_dict()
    payload["skipped"] = False
    return payload


def _record_state(record: GeneratedScript) -> None:
    state = _read_state()
    scripts = state.setdefault("scripts", {})
    scripts[record.mode] = {
        "mode": record.mode,
        "name": record.name,
        "model_path": record.model_path,
        "ps1_path": record.ps1_path,
        "sh_path": record.sh_path,
        "command_line": record.command_line,
        "params": record.params,
        "warnings": record.warnings,
        "updated_at": _now(),
    }
    state["last_scan"] = _now()
    _write_state(state)


def generate_all_launch_scripts(
    *,
    project_root: str | Path | None = None,
    model_dirs: list[str | Path] | None = None,
    config: AppConfig | None = None,
    overwrite: bool = True,
) -> ScanResult:
    """Scan the model folders and (re)generate a launch script for each one.

    Profiles already in ``models.json`` use their resolved parameters. New
    models (anything discovered on disk that does not have a manifest entry
    yet) get a starter script with sensible defaults so the dashboard can
    launch them immediately instead of showing them as "needs setup".
    """

    app_config = config or AppConfig.load()
    root = Path(project_root).expanduser().resolve() if project_root else find_project_root()
    if model_dirs:
        parsed_model_dirs = [Path(path).expanduser() for path in model_dirs]
    elif app_config.model_dirs:
        parsed_model_dirs = [Path(path).expanduser() for path in app_config.model_dirs]
    else:
        parsed_model_dirs = None

    resolved_profiles = resolve_profiles(project_root=root, model_dirs=parsed_model_dirs)
    discovered_models = discover_models(parsed_model_dirs, root)
    binary, _binary_warnings = _binary_path_for_script(root, app_config)

    result = ScanResult(
        scanned_model_count=len(discovered_models),
        profile_count=len(resolved_profiles),
        scanned_at=_now(),
    )

    handled_modes: set[str] = set()
    handled_model_paths: set[str] = set()

    # Track models.json so we can repair broken script references and register
    # newly discovered models as launchable profiles.
    manifest_doc = _load_manifest_doc(root)
    manifest_models = manifest_doc["models"]
    manifest_by_mode = {str(entry.get("mode")): entry for entry in manifest_models if entry.get("mode")}
    manifest_dirty = False

    # Models pulled in as speculative drafts must never get a standalone script.
    draft_paths: set[str] = set()
    for profile in resolved_profiles:
        draft_model = str(profile.params.get("draft_model", "")).strip()
        if draft_model:
            draft_paths.add(_norm_path(draft_model))

    for profile in resolved_profiles:
        if not profile.model or not profile.model.get("path"):
            result.skipped.append(
                {
                    "mode": profile.mode,
                    "reason": "Profile model could not be resolved against discovered files.",
                }
            )
            continue
        model_path = profile.model["path"]
        try:
            payload = generate_launch_script(
                mode=profile.mode,
                model_path=model_path,
                params=dict(profile.params),
                project_root=root,
                config=app_config,
                binary_path=binary,
                name=profile.name or profile.mode,
                overwrite=overwrite,
            )
        except OSError as exc:
            result.errors.append({"mode": profile.mode, "error": str(exc)})
            continue
        if payload.get("skipped"):
            result.skipped.append({"mode": profile.mode, "reason": "Already exists."})
        else:
            result.generated.append(
                GeneratedScript(
                    mode=payload["mode"],
                    name=payload["name"],
                    model_path=payload["model_path"],
                    ps1_path=payload["ps1_path"],
                    sh_path=payload["sh_path"],
                    command_line=payload["command_line"],
                    params=payload.get("params", {}),
                    warnings=payload.get("warnings", []),
                )
            )
        # Repair a broken manifest script reference so resolution can pin an
        # exact model path (confidence 1.0) instead of fuzzy matching.
        entry = manifest_by_mode.get(profile.mode)
        if entry is not None and not profile.profile.get("script_exists"):
            new_script = Path(payload["ps1_path"]).name
            if entry.get("script") != new_script:
                entry["script"] = new_script
                manifest_dirty = True

        handled_modes.add(profile.mode)
        handled_model_paths.add(str(Path(model_path).expanduser().resolve()).lower())

    # Generate starter scripts for any newly added models that are not
    # described in models.json yet.
    for model in discovered_models:
        try:
            resolved_path = str(Path(model.path).expanduser().resolve()).lower()
        except OSError:
            resolved_path = str(model.path).lower()
        if resolved_path in handled_model_paths:
            continue
        if resolved_path in draft_paths or _is_draft_model(model.path):
            result.skipped.append(
                {
                    "mode": _safe_slug(model.name or Path(model.path).stem),
                    "reason": "Draft/speculative companion model; no standalone server script.",
                }
            )
            continue
        mode = _safe_slug(model.name or Path(model.path).stem)
        if mode in handled_modes:
            # Two models collapsed to the same slug; disambiguate with a short hash.
            mode = f"{mode}-{model.id[:6]}"
        params = _default_params_for_model(model.to_dict(), app_config)
        try:
            payload = generate_launch_script(
                mode=mode,
                model_path=model.path,
                params=params,
                project_root=root,
                config=app_config,
                binary_path=binary,
                name=model.name,
                overwrite=overwrite,
            )
        except OSError as exc:
            result.errors.append({"mode": mode, "error": str(exc)})
            continue
        if payload.get("skipped"):
            result.skipped.append({"mode": mode, "reason": "Already exists."})
        else:
            result.generated.append(
                GeneratedScript(
                    mode=payload["mode"],
                    name=payload["name"],
                    model_path=payload["model_path"],
                    ps1_path=payload["ps1_path"],
                    sh_path=payload["sh_path"],
                    command_line=payload["command_line"],
                    params=payload.get("params", {}),
                    warnings=payload.get("warnings", []),
                )
            )
        # Register the newly discovered model as a launchable profile so the
        # dashboard surfaces it with an exact (script-pinned) model match.
        if root and mode not in manifest_by_mode:
            new_entry = {
                "mode": mode,
                "name": model.name or mode,
                "description": "Auto-generated from discovered model",
                "script": Path(payload["ps1_path"]).name,
                "recommended_params": _manifest_params(params),
            }
            manifest_models.append(new_entry)
            manifest_by_mode[mode] = new_entry
            manifest_dirty = True

        handled_modes.add(mode)
        handled_model_paths.add(resolved_path)

    if manifest_dirty and root:
        manifest_doc["models"] = manifest_models
        try:
            _save_manifest_doc(root, manifest_doc)
        except OSError as exc:
            result.errors.append({"mode": "models.json", "error": str(exc)})

    state = _read_state()
    state["last_scan"] = result.scanned_at
    state["last_scan_summary"] = {
        "generated_count": len(result.generated),
        "skipped_count": len(result.skipped),
        "error_count": len(result.errors),
        "scanned_model_count": result.scanned_model_count,
        "profile_count": result.profile_count,
    }
    _write_state(state)
    return result


def list_launch_scripts() -> list[dict[str, Any]]:
    """List the launch scripts this module has generated.

    Driven by the tracked state rather than a directory glob, so co-located
    hand-written scripts (``switch-model.ps1`` and other infrastructure files
    that share ``<root>/scripts``) are never reported as model launch scripts.
    """

    state = _read_state()
    out: list[dict[str, Any]] = []
    for record in state.get("scripts", {}).values():
        mode = record.get("mode")
        if not mode:
            continue
        ps1_path = Path(record.get("ps1_path", ""))
        sh_path = Path(record.get("sh_path", "")) if record.get("sh_path") else ps1_path.with_suffix(".sh")
        entry = dict(record)
        entry["ps1_path"] = str(ps1_path)
        entry["sh_path"] = str(sh_path)
        entry["sh_exists"] = sh_path.is_file()
        entry["exists"] = ps1_path.is_file()
        out.append(entry)
    return sorted(out, key=lambda item: str(item.get("mode")))


def delete_launch_script(mode: str) -> bool:
    """Delete the generated scripts (ps1 + sh + state entry) for ``mode``."""

    slug = _safe_slug(mode)
    ps1 = script_dir() / f"{slug}.ps1"
    sh = script_dir() / f"{slug}.sh"
    removed = False
    if ps1.is_file():
        ps1.unlink()
        removed = True
    if sh.is_file():
        sh.unlink()
        removed = True
    state = _read_state()
    scripts = state.get("scripts", {})
    if mode in scripts:
        scripts.pop(mode, None)
        state["scripts"] = scripts
        _write_state(state)
        removed = True
    return removed


def launch_scripts_scan_summary() -> dict[str, Any]:
    """Return metadata about the most recent scan plus the live file list."""

    state = _read_state()
    return {
        "last_scan": state.get("last_scan"),
        "last_scan_summary": state.get("last_scan_summary"),
        "scripts": list_launch_scripts(),
        "scripts_dir": str(script_dir()),
    }


def startup_autoscan_if_enabled(config: AppConfig | None = None) -> ScanResult | None:
    """Run a startup scan if the user has it enabled.

    Returns the ``ScanResult`` for the scan, or ``None`` when disabled.
    """

    app_config = config or AppConfig.load()
    if not (app_config.auto_scan_on_startup and app_config.auto_generate_launch_scripts):
        return None
    return generate_all_launch_scripts(config=app_config)


__all__ = [
    "GeneratedScript",
    "ScanResult",
    "delete_launch_script",
    "generate_all_launch_scripts",
    "generate_launch_script",
    "launch_scripts_dir",
    "launch_scripts_scan_summary",
    "list_launch_scripts",
    "script_dir",
    "startup_autoscan_if_enabled",
]
